# Stage 1: Build the Angular app
FROM node:20.19.6-slim AS build

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --legacy-peer-deps

# Install Nx CLI globally
RUN npm install -g nx

# Copy the Nx workspace
COPY . .

ENV NX_DAEMON=false
# Build the Angular app
RUN npx nx build admin-app --configuration=development

# Stage 2: Serve the Angular app with a lightweight web server
FROM nginx:1.29.4-alpine

# Remove the default Nginx static content
RUN rm -rf /usr/share/nginx/html/*

# Copy the built Angular app from the build stage to the Nginx HTML directory
COPY --from=build /app/dist/apps/admin-app/browser /usr/share/nginx/html/app

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
